const adjectives = {
  a: ['adorable', 'aggressive', 'annoyed'],
  b: ['bewildered', 'bizzare', 'blue-eyed', 'bored', ''],
  c: ['cautious', 'careless', 'caring', 'charming', 'clumsy', 'conscious'],
  d: ['damaged', 'demonic', 'distressed', 'dizzy'],
  e: ['eager', 'elegant', 'enchanting', 'enormous'],
  f: ['fabulous', 'famous', 'faded', 'fertile', 'frightened'],
  g: ['glamorous', 'gifted', 'godly', 'grotesque', 'grumpy'],
  h: [
    'hungry',
    'hard-to-find',
    'harmonious',
    'hateful',
    'helpless',
    'homeless',
    'hysterical',
  ],
  i: [
    'ill-informed',
    'imaginary',
    'imperfect',
    'impolite',
    'infamous',
    'inexpensive',
    'intelligent',
    'itchy',
  ],
  j: ['joyful', 'juicy', 'jobless', 'jealous', 'jumpy'],
  k: ['kaput', 'keen', 'kind'],
  l: [
    'lavish',
    'lazy',
    'loving',
    'likable',
    'literate',
    'lonely',
    'loud',
    'lyrical',
    'lucky',
  ],
  m: [
    'mad',
    'manly',
    'macho',
    'married',
    'majestic',
    'mighty',
    'merfciful',
    'moody',
  ],
  n: ['neat', 'needy', 'nervous', 'nimble', 'nonchalant'],
  o: [
    'obedient',
    'obnoxious',
    'observant',
    'odd',
    'ordinary',
    'organic',
    'outgoing',
  ],
  p: [
    'potent',
    'peaceful',
    'perfect',
    'precious',
    'proud',
    'pathetic',
    'panicky',
  ],
  q: ['questionable', 'quick', 'quirky', 'quiet'],
  r: [
    'radical',
    'rapid',
    'rebel',
    'reflective',
    'regular',
    'rotten',
    'robust',
    'rough',
    'responsive',
    'relieved',
  ],
  s: [
    'scary',
    'second-hand',
    'selfish',
    'salty',
    'sarcastic',
    'shiny',
    'sparkling',
    'smiling',
    'superior',
  ],
  t: [
    'tacky',
    'tangible',
    'tasteless',
    'tender',
    'tame',
    'tasty',
    'thick',
    'tricky',
  ],
  u: ['unadvised', 'undesirable', 'unique', 'unsightly', 'used', 'uptight'],
  v: [
    'vicious',
    'vivid',
    'volatile',
    'vulgar',
    'victorious',
    'vengeful',
    'violent',
  ],
  w: [
    'wandering',
    'well-groomed',
    'whimsical',
    'wicked',
    'wild',
    'wise',
    'womanly',
    'wobbly',
  ],
  x: ['Very special'],
  y: ['yellow', 'yoyoing', 'yummy', 'youthful'],
  z: ['zippy', 'zealous', 'zen', 'zigzag', 'zazzy'],
};

const nouns = {
  a: [
    'axolotl',
    'armadillo',
    'arctic fox',
    'ant',
    'alpaca',
    'alligator',
    'akita',
    'apricot',
  ],
  b: [
    'bear',
    'bat',
    'beaver',
    'bee',
    'bird',
    'bison',
    'butterfly',
    'bumblebee',
  ],
  c: ['carp', 'cactus', 'clown', 'cockroach', 'chipmunk', 'crab', 'cricket'],
  d: ['dandelion', 'donkey', 'deer', 'dolphin', 'dwarf', 'dire wolf'],
  e: ['eel', 'eagle', 'elk', 'emu'],
  f: ['firefly', 'fish', 'fly', 'falcon', 'fox', 'frog'],
  g: ['goat', 'giraffe', 'gibbon', 'goose', 'guinea pig'],
  h: ['halibut', 'hedgehog', 'hamster', 'horse', 'husky', 'human'],
  i: ['ibis', 'indian cobra', 'impala', 'ion'],
  j: ['jaguar', 'jackal', 'jellyfish', 'jumping spider'],
  k: ['koala', 'komodo dragon', 'kiwi', 'kangaroo', 'koi fish'],
  l: [
    'labrador',
    'lizardfish',
    'lion',
    'lizard',
    'lemur',
    'lobster',
    'leopard',
    'lynx',
  ],
  m: ['mamba', 'megalodon', 'manatee', 'mongoose', 'moose', 'mouser'],
  n: ['narwhal', 'newt', 'night snake', 'needlefish', 'nightingale'],
  o: ['ocelot', 'octopus', 'owl', 'oyster', 'okapi', 'otter'],
  p: [
    'paddlefish',
    'parrot',
    'pelican',
    'papillon',
    'penguin',
    'pigeon',
    'platypus',
    'puma',
  ],
  q: ['queen snake', 'quartz', 'queen'],
  r: ['rabbit', 'rainbow', 'reindeer', 'rose', 'rooster', 'rockfish'],
  s: [
    'salmon',
    'sea lion',
    'seal',
    'seahorse',
    'sheep',
    'sloth',
    'snail',
    'sparrow',
    'spider',
    'squirell',
  ],
  t: ['tapir', 'tarantula', 'termite', 'tiger', 'terrier', 'tuna'],
  u: ['umbrella', 'ural owl'],
  v: ['vampire', 'vulture', 'vinegar', 'vine snake'],
  w: ['wasp', 'weasel', 'walrus', 'wild board', 'wombat', 'wolf'],
  x: ['x-ray'],
  y: ['yak', 'yoyo', 'Yorkshire terrier', 'Yetti'],
  z: ['zebra', 'zircon'],
};

export { adjectives, nouns };
