/* eslint-disable */
// ms
const COIN_SPIN_DURATION = 4200;

// seconds
const QUICK_GAME_DURATION = 2 * 60 + 30;
const RANKED_GAME_DURATION = 5 * 60;

export { COIN_SPIN_DURATION, QUICK_GAME_DURATION, RANKED_GAME_DURATION };
