/* eslint-disable */
// ms
const COIN_SPIN_DURATION = 4200;

// seconds
const QUICK_GAME_DURATION = 2 * 60 + 30;
const RANKED_GAME_DURATION = 5 * 60;

// elo rank milestones
const POTATO_MILESTONE = 0;
const WARRIOR_MILESTONE = 1100;
const SAMURAI_MILESTONE = 1600;
const CHAMPION_MILESTONE = 2200;

export {
  COIN_SPIN_DURATION,
  QUICK_GAME_DURATION,
  RANKED_GAME_DURATION,
  POTATO_MILESTONE,
  WARRIOR_MILESTONE,
  SAMURAI_MILESTONE,
  CHAMPION_MILESTONE,
};
